djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', include('inicio.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inicio/urls.py
from django.urls import path
from inicio import views

app_name = 'inicio'

urlpatterns = [
    path('', views.mi_vista, name='inicio'),
    path('sobre_nosotros', views.sobre_nosotros, name='sobre_nosotros'),
    path('/inicio/jugador/', views.JugadorListView.as_view, name='lista_jugadores'),
    path('/inicio/jugador/crear/', views.JugadorCreateView.as_view, name='crear_jugador'),
    path('/inicio/jugador/<int:pk>/', views.JugadorDetailView.as_view, name='detalle_jugador'),
    path('/inicio/jugador/<int:pk>/modificar/', views.JugadorUpdateView.as_view, name='modificar_jugador'),
    path('/inicio/jugador/<int:pk>/eliminar/', views.JugadorDeleteView.as_view, name='eliminar_jugador'),


]

usuarios/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from usuarios import views

app_name = 'usuarios'


urlpatterns = [
    path('login/', views.login , name='login'),
    path('registro/', views.registro, name='registro'),
    path('perfil/editar/', views.editar_perfil, name='editar_perfil'),
    path('perfil/editar/cambiar_clave', views.CambiarClave.as_view(), name='cambiar_clave'),   
    path('logout/', LogoutView.as_view(template_name='usuarios/logout.html'), name='logout')
]

inicio/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Jugador(models.Model):
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    descripcion= RichTextField()
    fecha_nacimiento = models.DateField()
    posicion = models.CharField(max_length=20)
    foto_de_identificacion = models.ImageField(upload_to='avatares', null=True, blank=True)
    
    def __str__(self):
        return f"{self.nombre} - {self.posicion}"
    

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class InfoExtra(models.Model):
    avatar = models.ImageField(upload_to='avatares', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    informacion = models.CharField(max_length=40)

inicio/forms.py
from django import forms


class CreacionJugadorFormulario(forms.Form):
    nombre = forms.CharField(max_length=20)
    edad = forms.IntegerField()
    fecha_nacimiento = forms.DateField(max_length=20)
    posicion = forms.CharField(max_length=20)
    foto_de_identificacion = forms.ImageField(upload_to='avatares', null=True, blank=True)

    
class BuscarJugador(forms.Form):
    nombre = forms.CharField(max_length=20, required=False)

usuarios/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms



class FormularioRegistro(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {k: '' for k in fields}
        
        
        
        
class EdicionPerfil(UserChangeForm):
    password = None
    email = forms.EmailField()
    first_name = forms.CharField(label='Nombre', max_length=30)
    first_name = forms.CharField(label='Apellido', max_length=30)
    
    avatar = forms.ImageField(required=False)
    
    
    class Meta:
        model = User
        fields = [ 'email', 'first_name', 'last_name', 'avatar']
    
    
    

inicio/views.py
from django.shortcuts import render 

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from inicio.models import Jugador


def mi_vista(request):
    return render(request, 'inicio/inicio.html')

def sobre_nosotros(request):
    return render(request, 'inicio/sobre_nosotros.html')

class JugadorListView(ListView):
    model = Jugador
    template_name = "inicio/lista_jugadores.html"

class JugadorDetailView(DetailView):
    model = Jugador
    template_name = "inicio/detalle_jugador.html"


class JugadorCreateView(CreateView):
    model = Jugador
    template_name = "inicio/crear_jugador.html"
    fields = ['nombre','edad','fecha_nacimiento','posicion', 'descripcion', 'foto_de_identificacion',]
    success_url = '/jugador/'
    

class JugadorUpdateView(LoginRequiredMixin, UpdateView):
    model = Jugador
    template_name = "inicio/modificar_jugador.html"
    fields = ['nombre','edad','fecha_nacimiento','posicion','descripcion', 'foto_de_identificacion',]
    success_url = '/jugador/'


class JugadorDeleteView(LoginRequiredMixin, DeleteView):
    model = Jugador
    template_name = "inicio/eliminar_jugador.html"
    success_url = '/jugador/'

usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as login_django
from usuarios.forms import FormularioRegistro, EdicionPerfil
from django.contrib.auth.decorators import login_required
from usuarios.models import InfoExtra
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def login(request):
    
    if request.method == 'POST':
        fromulario = AuthenticationForm(request, data=request.POST)
        
        if fromulario.is_valid():
            usuario = fromulario.cleaned_data.get('username')
            clave = fromulario.cleaned_data.get('password')
            
            user = authenticate(username=usuario, password=clave)
            
            login_django(request, user)
            InfoExtra.objects.get_or_create(user=user)
            
            return redirect('inicio:inicio')
        else:
            
           return render(request, 'usuarios/login.html', {'from': fromulario})
    
    fromulario = AuthenticationForm()
    return render(request, 'usuarios/login.html', {'from': fromulario})


def registro(request):
       
    if request.method == 'POST':
        fromulario = FormularioRegistro(request.POST)
        
        if fromulario.is_valid():
            fromulario.save()

            return redirect('usuarios:login')
        else:
            
           return render(request, 'usuarios/registro.html', {'from': fromulario})
    
    fromulario = FormularioRegistro()
    return render(request, 'usuarios/registro.html', {'from': fromulario})

@login_required
def editar_perfil(request):


    if request.method == 'POST':
        fromulario = EdicionPerfil(request.POST, request.FILES,  instance=request.user)
        
        if fromulario.is_valid():
            
            if fromulario.cleaned_data.get('avatar'):
                request.user.infoextra.avatar = fromulario.cleaned_data.get('avatar')
                request.user.infoextra.save()
            
            fromulario.save()

            return redirect('usuarios:editar_perfil')
        else:
            
           return render(request, 'usuarios/editar_perfil.html', {'from': fromulario})
    
    fromulario = EdicionPerfil(initial={'avatar': request.user.infoextra.avatar}, instance=request.user)
    return render(request, 'usuarios/editar_perfil.html', {'from': fromulario})


class CambiarClave(LoginRequiredMixin, PasswordChangeView):
    template_name = 'usuarios/cambiar_clave.html'
    success_url = reverse_lazy('usuarios:editar_perfil')

inicio/templates/inicio/crear_jugador.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Crear Jugador</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Creando Jugadores</h1>
{% endblock h1_header %}


{% block contenido %}

<form action={% url 'inico:crear_jugador' %} method="post">
    {% csrf_token %}
    <table>
        {{from.media}}
        {{from}}
    </table>

    <button>Crear</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/detalle_jugador.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Jugador</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Jugador: {{jugador}}</h1>
{% endblock h1_header %}


{% block contenido %}


<ul> 
    <li>Nombre: {{jugador.nombre}}</li>
    <li>Edad: {{jugador.edad}}</li>
    <li>Decripcion: {{jugador.descripcion | safe}}</li>
    <li>Fecha de Nacimiento: {{jugador.fecha_nacimiento}}</li>
    <li>Posicion: {{jugador.posicion}}</li>
    <li>Foto de Identificacion: {{jugador.foto_de_identificacion}}</li>
    

</ul>
<a href= {% url 'inicio:modificar_jugador' paleta.id %}>Modificar Jugador </a>  . <a href= {% url 'inicio:eliminar_jugador' paleta.id %}> Eliminar Jugador </a>

{% endblock contenido %}

inicio/templates/inicio/eliminar_jugador.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Eliminar Jugador</title>
{% endblock title_head %}

{% block h1_header %}   
    <h1>Eliminando Jugadores</h1>
{% endblock h1_header %}


{% block contenido %}

<form action={% url 'inico:eliminar_jugador' jugador.id %} method="post">
    {% csrf_token %}
    <h4>Quiere eliminar los datos de {{jugador}}?</h4>
    <button>Confirmar</button>
    <button>Eliminar</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/inicio.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Pagina principal</h1>
{% endblock h1_header %}


{% block contenido %}
{% endblock contenido %}

inicio/templates/inicio/lista_jugadores.html
{% extends 'genericos/base.html' %}

{% block title_head %}
<title>Jugadores</title>
{% endblock title_head %}

{% block h1_header %}
<h1>Listado de Jugadores</h1>
{% endblock h1_header %}


{% block contenido %}

<a href= {% url 'inicio:crear_jugador'%}>Crear jugador</a>

{% if object_list %}

<ul> 
    {% for jugador in object_list %}
    <li><a href= {% url 'inicio:detalle_jugador' paleta.id %}>{{jugador}}</a> </li>
    <a href= {% url 'inicio:modificar_jugador' paleta.id %}>Modificar Jugador </a>  . <a href= {% url 'inicio:eliminar_jugador' paleta.id %}> Eliminar Jugador </a>
    
    {% endfor %}
</ul>
{% else %}
<h3>No se encontraron Jugadores</h3>
{% endif %}
{% endblock contenido %}

inicio/templates/inicio/modificar_jugador.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Modificar Jugador</title>
{% endblock title_head %}

{% block h1_header %}   
    <h1>Modificando Jugadores</h1>
{% endblock h1_header %}


{% block contenido %}

<form action={% url 'inico:modificar_jugador' jugador.id %} method="post">
    {% csrf_token %}
    <table>
        {{form.media}}
        {{from}}
    </table>

    <button>Modificar</button>
</form>

{% endblock contenido %}

inicio/templates/inicio/sobre_nosotros.html
{% extends 'genericos/base.html' %}

{% block title_head %}
                    <title>Inicio</title>
{% endblock title_head %}

{% block h1_header %}
                    <h1>Pagina principal</h1>
{% endblock h1_header %}


{% block contenido %}
Un sitio web dedicado a proporcionar información sobre los mejores jugadores de fútbol de todo el mundo. Nos enorgullece ofrecer listados detallados y precisos sobre los jugadores más destacados, incluyendo sus estadísticas, habilidades y logros.
{% endblock contenido %}

templates/genericos/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block title_head %}
        <title>Template Base</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href={% static 'inicio/css/styles.css' %} rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href={% url 'inicio:inicio' %}>Inicio</a>                
                <a class="navbar-brand" href={% url 'inicio:lista_jugadores' %}>Jugadores</a>
                {% if request.user.is_authenticated %}
                <a class="navbar-brand" href={% url 'usuarios:editar_perfil' %}>{{request.user.username}}</a>
                <a class="btn btn-primary" href={% url 'usuarios:logout' %}>Logout</a>
                {% else %}
                <a class="btn btn-primary" href={% url 'usuarios:login' %}>Login</a>
                <a class="btn btn-primary" href={% url 'usuarios:registro' %}>Registrarse</a>
                {% endif %}



                
            </div>
        </nav>
        <!-- Masthead-->
        {% block header %}
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                           
                            {% block h1_header %}
                            <h1 class="mb-5"> h1 base</h1>
                            {% endblock h1_header %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock header %}
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href={% url 'inicio:sobre_nosotros' %}>Sobre Nosotros</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src={% static 'inicio/js/scripts.js' %}></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

usuarios/templates/usuarios/cambiar_clave.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Cambiar Clave</title>
{% endblock title_head %}

{% block h1_header %}
    <h1>Cambiar Clave</h1>
{% endblock h1_header %}


{% block contenido %}

{% if form.error %}
<p>El formulario no es válido.</p>
{% endif %}


<form action={% url 'usuarios:cambiar_clave' %} method="post">

    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button>Cambiar</button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/editar_perfil.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Editar perfil</title>
{% endblock title_head %}

{% block h1_header %}
    <h1>Editar perfil</h1>
{% endblock h1_header %}


{% block contenido %}

{% if form.error %}
<p>El formulario no es válido.</p>
{% endif %}


<form action={% url 'usuarios:editar_perfil' %} method="post" enctype='multipart/form-data'>

    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button type='button'><a href={% url 'usuarios:cambiar_clave' %}> Cambiar Clave </a></button>
    <button>Editar</button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/login.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Login</title>
{% endblock title_head %}

{% block h1_header %}
    <h1>Login</h1>
{% endblock h1_header %}


{% block contenido %}

{% if form.error %}
<p>Usuario no esta logueado</p>
{% endif %}


<form action={% url 'usuarios:login' %} method="post">

    {% csrf_token %}
    <table>
        {{form}}
    </table>

    <button>Loguearse</button>
</form>
{% endblock contenido %}

usuarios/templates/usuarios/logout.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Logout</title>
{% endblock title_head %}

{% block h1_header %}
    <h1>La sesión ha sido cerrada con éxito.</h1>
{% endblock h1_header %}


{% block contenido %}
{% endblock contenido %}

usuarios/templates/usuarios/registro.html
{% extends 'genericos/base.html' %}

{% block title_head %}
    <title>Registrarse</title>
{% endblock title_head %}

{% block h1_header %}
    <h1>Registrarse</h1>
{% endblock h1_header %}


{% block contenido %}

{% if form.error %}
<p>Datos invalidos</p>
{% endif %}


<form action={% url 'usuarios:login' %} method="post">

    {% csrf_token %}
    <table>
        {{form}}
    </table>

    <button>Registrarse</button>
</form>
{% endblock contenido %}